### ISSUE TITLE
C-FLOAT errors when attempting to use al:draw-filled-rectangle

### ISSUE THREAD

**Issue by iamgreaser** [resttime/cl-liballegro#10]
Hey there.

I'm trying to get `al:draw-filled-rectangle` working but I'm hitting `cffi:translate-into-foreign-memory` issues. `al:put-pixel` works a charm. It's probably due to how `c-float` works in this regard, as while `al:draw-filled-rectangle` uses `c-float`, `al:put-pixel` uses `int`.

I've installed it through QuickLisp on SBCL, and it seems to be the 2017-01-24-git version. I am running on Linux on amd64. I suspect there may be a broken definition somewhere.

```
* (progn (al:clear-to-color (al:map-rgb 0 0 85)) (al:draw-filled-rectangle 100 110 200 150 (al:map-rgb 255 255 255)) (al:flip-display))

debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {100197E573}>:
  There is no applicable method for the generic function
    #<STANDARD-GENERIC-FUNCTION CFFI:TRANSLATE-INTO-FOREIGN-MEMORY (5)>
  when called with arguments
    (100 #<CL-LIBALLEGRO::C-FLOAT {1001A889C3}>
     #.(SB-SYS:INT-SAP #X7FFFF700FFC8)).
```

For a simpler test, `al:map-rgb` works fine, while `al:map-rgb-f` complains with the same error.

Am I doing something wrong?

**Comment by resttime** [comment]
I did find some problems with functions that weren't named properly related to the al:map-rgb-f in graphics.lisp but I may need to look more into why al:draw-filled-rectangle has an issue since it looks like you are calling it correctly and I can't seem to find a problem in the library on first inspection. As for a fun fact, the c-float type and pals is meant to emulate the automatic type conversion that c does like when passing a double to a function expecting an int. I'm busy currently but I'll try to fully address this by the weekend. Thanks for the bringing up the issue.

**Comment by resttime** [comment]
For now, I pushed a commit that should at least address the ```al:map-rgb-f``` issue that you can test.

Assuming unfamiliarity with Quicklisp, you can clone the git repo and symlink/copy to a local-projects folder before it gets updated in the Quicklisp repo (I think that happens the end of every month?).
```
Can I load a local project that isn't part of Quicklisp?
Yes. The easiest way is to put the project's directory in Quicklisp's local-projects directory. For example:

    $ cd ~/quicklisp/local-projects/
    $ git clone git://github.com/xach/format-time.git

The project will then be loadable via (ql:quickload "format-time")

Also, any system file that can be found via ASDF's source registry system can be loaded with ql:quickload.

For example, if you have a system file my-project.asd in /projects/my-project/, you can do something like this:

    (push #p"/projects/my-project/" asdf:*central-registry*)
    (ql:quickload "my-project")

If my-project depends on systems that are available via Quicklisp that are not already installed, they will be automatically installed
```

**Comment by resttime** [comment]
Decided to spend some time looking into it and the error with TRANSLATE-INTO-FOREIGN-MEMORY should be fixed.

**Comment by resttime** [comment]
Assuming that everything is fixed I will be closing the issue and have updated the examples/simple-window.lisp to produce something similar to your code:

![done](https://user-images.githubusercontent.com/2598904/32535461-bc43ba8c-c41f-11e7-961c-0476ebba41b6.png)

**Comment by resttime** [comment]
Ref: #9 Activity heartbeat
