### ISSUE TITLE
Adding to Quicklisp

### ISSUE THREAD

**Issue by resttime** [resttime/cl-liballegro#17]
cl-liballegro was removed from quicklisp repos at some point. It should be added back in within a month I think: 

https://github.com/quicklisp/quicklisp-projects/issues/1821

**Comment by lockie** [comment]
I've just successfully reinstalled cl-liballegro from quicklisp, so it works for me.
Have you launched `(ql:update-dist "quicklisp")` on machine in question? This might be the problem.

**Comment by resttime** [comment]
Oh you're right, looks like it was added in a few days ago too. Neat
http://blog.quicklisp.org/
