### ISSUE TITLE
Audio stream events

### ISSUE THREAD

**Issue by ariSunz** [resttime/cl-liballegro#30]
Correct me if I'm wrong, but is there not a way catch ALLEGRO_AUDIO_EVENT_TYPE (and more precisely, ALLEGRO_EVENT_AUDIO_STREAM_FRAGMENT) yet?

Also, semi related, I found what seems to be a typo in the audio FFI code: the binding for al_get_audio_stream_event_source is "get-sudio-stream-event-source"

https://github.com/resttime/cl-liballegro/blob/f1337509d443641faade44e07057d897b42a9b83/src/ffi-functions/addons/audio.lisp#L159

**Comment by resttime** [comment]
Looks like there isn't, I'll work on adding it in when I get more time.

And yup typo is there for easy fix and pushed, thanks!

**Comment by resttime** [comment]
Event type should be added now with c7fc389. 

Fix was simpler than first thought since it's been a while. Usage ends up as another event type that gets emitted o check for:

```lisp
:-kcm-stream-feeder-quit-event-type
:audio-stream-fragment
:audio-stream-finished
:audio-recorder-fragment
```

**Comment by ariSunz** [comment]
Awesome, thank you so much!
