### ISSUE TITLE
Not an issue but ...

### ISSUE THREAD

**Issue by RyanBurnside** [resttime/cl-liballegro#33]
This is a very nice wrapper.
People often get dismayed when they discover a new (old) language and can't get anything on the screen.
Keep up the good work! You do a service to the Common Lisp community maintaining this.

We are currently working on a game using it and it's very fun. Much easier than SDL2 + OpenGL.
I think you should get the word out about this, it should probably be one of the defacto ways of doing Lisp games. Along with cl-bodge (I also really respect borodust's work)

**Comment by resttime** [comment]
Thanks, I'm glad to know it's found use aside from myself! I started these bindings to be a simpler solution than piecing together multiple libraries at the time. It leans on the functionality of Allegro 5, tries not to be too clever, and facilitates usage/contribution by organizing according to the [documentation](https://liballeg.org/a5docs/trunk/) of [the actual library](https://github.com/liballeg/allegro5) which itself is still in active development so new features remain possible even if these bindings are stable enough to look dead :joy: 

And cool! Let me know how the game goes and it can be added to the readme as an example if there's a link. I can usually provide some general support here that's specific about the wrapper too. Occasionally I pop into a lisp hangout to mention it exists and have left links around.

**Comment by resttime** [comment]
Cleaning up issues a bit, this one looks safe to close. Feel free to open a new one.
