### ISSUE TITLE
Gray streams for files

### ISSUE THREAD

**Issue by lockie** [resttime/cl-liballegro#35]
Hey @resttime! Hope you're well. I was wondering if you'd be willing to accept a pull request adding the Gray streams functionality for liballegro [file APIs](https://liballeg.org/a5docs/trunk/file.html) — I know that's an extra maintenance burden and extra [trivial-gray-streams](https://github.com/trivial-gray-streams/trivial-gray-streams) dependency, but that'd be real nice wrapper to have. It is literally [those 80 lines](https://gitlab.com/lockie/d2clone-kit/-/blob/d26d489c66b7148bca1d7694c574acda3f358063/src/fs.lisp#L149-227), perhaps I'd put those in separate lisp file, along `interface.lisp`.
If the answer is no, no worries — I'd just post it as a separate tiny library to Quicklisp. I'm just too lazy doing that :stuck_out_tongue_winking_eye:

**Comment by resttime** [comment]
Heya, looks like it'd be a good addition to me! There's already a few other
dependencies like trivial-garbage and trivial-main-thread in use. Putting
it in a separate file next to interface.lisp makes sense as it'd be
considered for convinience and optional to use. Just add a bit of
documentation to the readme too so users know about it.

**Comment by lockie** [comment]
Awesome, thanks! I'm on it :ok_hand:
