### ISSUE TITLE
What Is Wrong With This Code?

### ISSUE THREAD

**Issue by Oleg-Harput** [resttime/cl-liballegro#38]
I want to use `al:show-native-message-box` function, so i wrote:
...
```
`(setf *created-display* (al:create-display 800 600))

(c:with-foreign-string (text "MessageBox Title") 
  (al:show-native-message-box *created-display* 
			      text
			      (c:foreign-enum-value 'al::messagebox-flags :error)
			      (c:foreign-enum-value 'al::filechooser-modes :show-hidden)
			      (c:null-pointer)
			      (c:null-pointer)))
(al:destroy-display *created-display*)`
```

But i get the Error: "2 is not a Lisp string or pointer." 
If you can please write the true form of this code 
Thanks.

exact code: 

```
`(in-package #:al-tut)
 
(defvar *created-display*)

(defun main ()
  (unless (al:init)
    (al:show-native-message-box (c:null-pointer) (c:null-pointer) (c:null-pointer) "allegro init failed." (c:null-pointer) (c:null-pointer))
    'AL-INIT-FAILED)
  (setf *created-display* (al:create-display 800 600))
  (unless *created-display*
    (al:show-native-message-box (c:null-pointer) (c:null-pointer) (c:null-pointer) "window init failed. " (c:null-pointer) (c:null-pointer))
    'AL-CREATE-DISPLAY-FAILED)
  (c:with-foreign-string (text "MessageBox Title") 
    (al:show-native-message-box *created-display* 
				text
				(c:foreign-enum-value 'al::messagebox-flags :error)
				(c:foreign-enum-value 'al::filechooser-modes :show-hidden)
				(c:null-pointer)
				(c:null-pointer)))
  (al:destroy-display *created-display*))
```
`

**Comment by lockie** [comment]
Have a closer look to the [function signature](https://liballeg.org/a5docs/trunk/native_dialog.html#al_show_native_message_box). The messagebox in liballegro has title, text and also the heading:

![messagebox screenshot](https://github.com/resttime/cl-liballegro/assets/160056/1bc65b4d-084b-4e85-b18f-25945566a53b)

The code to display this is the following:

```lisp
(cffi:with-foreign-strings ((title "Title")
                            (text "Text")
                            (heading "Heading"))
           (al:show-native-message-box (cffi:null-pointer) title heading text
                                       (cffi:null-pointer) 0))
```

P.S. you might want to use triple quotes to format code on github.

**Comment by resttime** [comment]
Thanks for the support lockie!

One thing I'll add to the answer is that CFFI does allow automatic conversion between Lisp and C Strings with dynamic extent so cleanup is done automatically at the end of the function call: https://cffi.common-lisp.dev/manual/html_node/Other-Types.html

A call can be like:
`(al:show-native-message-box (cffi:null-pointer) "Title" "Heading" "Text" (cffi:null-pointer) 0)`

Figured I might as well add a quick example how to use the message box too:
[62e006d](https://github.com/resttime/cl-liballegro/commit/62e006d9c63f5cfb34c5f4b5bb66f327488b8584)

Issue can be considered resolved so I'll be closing it to cleanup. Feel free to open another for support needed.
