### ISSUE TITLE
*system* not bound to value in lispy interface

### ISSUE THREAD

**Issue by justjoheinz** [resttime/cl-liballegro#44]
System : Mac OS M1, sbcl 2.4.1

When using the lispy interface (example 002), sbcl reports `The variable CL-LIBALLEGRO::*SYSTEM* is unbound.` and the example fails to start. 

Given the current code of `run-system` : 
```lisp 
(defun run-system (system)
  (trivial-main-thread:with-body-in-main-thread ()
    (let ((*system* system))
      (float-features:with-float-traps-masked
          (:divide-by-zero :invalid :inexact :overflow :underflow)
        (run-main 0 (null-pointer) (callback run-system-main))))))
``` 

the let binding seems to be to late, see also  the chapter [Create a thread: print a message onto the top-level](https://lispcookbook.github.io/cl-cookbook/process.html) in the cookbook. However fixing it by binding *system* earlier, does not work (for me). It seems the binding is being overridden again in the thread. 

What works (for me) is:
```
(defun run-system (system)
  (setq *system* system)
  (trivial-main-thread:with-body-in-main-thread ()
    (float-features:with-float-traps-masked
        (:divide-by-zero :invalid :inexact :overflow :underflow)
      (run-main 0 (null-pointer) (callback run-system-main)))))
```

However I a) do not understand why it works and the other solution not, and b) setting the global variable instead of using the binding does not seem very lispy to me. I also do not understand why this issue hasn't crept up earlier?

**Comment by resttime** [comment]
Hmmmm, unfortunately I don't have ready access to OSX while I run Linux.

The current implementation with the threads was a PR contributed by someone else on OSX. I think the idea behind the implementation was trying to reconcile passing a reference to `system` to a callback `run-system-main`. Then issue #39 was reported and verified on my Linux machine so I made a change to the order of the binding in a commit mentioned in that issue that "fixed" the example on my machine. Suppose it broke for OSX then. 

I'll try get my hands on an OSX to investigate more at some point

**Comment by justjoheinz** [comment]
I would be happy to test things for you, if you put them in a branch.

**Comment by resttime** [comment]
Great, thanks! Try the `fix-interface` branch the changes may have fixed it

**Comment by justjoheinz** [comment]
Works for me, it seems to use the setf/setq workaround. I would be happier if I understood why the let construct is not working, but for the time being it would be fine. Maybe put a comment in the source code, that this part is dodgy?

**Comment by resttime** [comment]
Alright wouldn't hurt to add a small comment

**Comment by resttime** [comment]
Bit of docs on binding special variables and threads https://www.sbcl.org/manual/#Special-Variables
