### ISSUE TITLE
audio system is not working out of the box (lispy interface)

### ISSUE THREAD

**Issue by justjoheinz** [resttime/cl-liballegro#45]
In the method `initialize-system` there should be a call to `(al:restore-default-mixer)` after the audio system has been initialized.

Otherwise calls to  `(al:play-audio-stream ...)` are silent. Ideally initialize system would also be exported, so that the behaviour can be customized.

**Comment by resttime** [comment]
Suggested changes implemented in: 51ba4c4b8cf05519824f8c75d688ebb1d3cd47d0
