### ISSUE TITLE
Keyboard bug with cffi or intended behaviour? 

### ISSUE THREAD

**Issue by justjoheinz** [resttime/cl-liballegro#47]
The example `002-lispy-interface.lisp` contains code for the key down handler:

```lisp 
(defmethod al:key-down-handler ((sys window))
  (let ((keyboard (cffi:mem-ref (al:event sys) '(:struct al:keyboard-event))))
    (print (getf keyboard 'al::keycode))
    (setf (previous-key sys) (getf keyboard 'al::keycode))))
```

this code works fine until I press the key (on a Mac keyboard) which contains the `^` and `°` symbols. It is right under the `esc` key and easy to hit.  The result is that an error is raised with the input sequence in the example below being `1`, `2`, `3`, `^`

```
ONE-LOGIC-FRAME 
:|1| 
ONE-LOGIC-FRAME 
:|2| 
:|3| 
ONE-LOGIC-FRAME 
CL-USER> 

0 is not defined as a value for enum type #<CFFI::FOREIGN-ENUM CL-LIBALLEGRO::KEYCODES>.
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [ABORT] abort thread (#<FOREIGN-THREAD "callback" RUNNING {7003910003}>)

Backtrace:
 0: (CFFI::%FOREIGN-ENUM-KEYWORD #<CFFI::FOREIGN-ENUM CL-LIBALLEGRO::KEYCODES> 0 :ERRORP T)
 1: ((:METHOD CFFI:TRANSLATE-FROM-FOREIGN (T CFFI::FOREIGN-STRUCT-TYPE)) #.(SB-SYS:INT-SAP #X600003ADC000) #<CL-LIBALLEGRO::KEYBOARD-EVENT-TCLASS CL-LIBALLEGRO:KEYBOARD-EVENT>) [fast-method]
 2: ((
 ```

The keyboard event example in https://github.com/liballeg/allegro5/blob/master/examples/ex_keyboard_events.c does not exhibit this behaviour. I cannot see any special error handling code there, so the question is whether something is to be done at the cl-liballegro side.

**Comment by resttime** [comment]
Hmmmm interesting, this falls under undefined behaviour. cl-liballegro translates enum keycodes to Lisp keywords. Where the enum keycodes are defined in the liballegro5 library [[1]](
https://github.com/liballeg/allegro5/blob/edcc50e85036e95474a31a7c75089b6b7653a4e5/include/allegro5/keycodes.h#L25), there is no corresponding value to 0 which is reflected in cl-liballegro [[2]](https://github.com/resttime/cl-liballegro/blob/cbec071009eb674c9d92583a4c3f01a969a7b49b/src/constants/keyboard.lisp#L4).

This can be "fixed" by adding a keycode/keyword for it. I dunno if that'd be considered valid although. Does the keycode for the key in the keyboard event example also equal to 0?

**Comment by resttime** [comment]
One candidate for a keyword could be `:(none)` if trying to adhere to liballegro5:

![image](https://github.com/resttime/cl-liballegro/assets/2598904/2c188f28-78d0-4af5-b382-4160423bbb84)

**Comment by justjoheinz** [comment]
I just had a look, the C lib also returns none and the code is 0. 

the C code has :

```c
const char *_al_keyboard_common_names[/* leave empty */] =
{
   "(none)",     "A",          "B",          "C",
   "D",          "E",          "F",          "G",
   ...
```

whereas the CL Code has

```lisp 
;; Keycodes
(defcenum keycodes
  (:a 1)
  (:b 2)
  (:c 3)
  (:d 4)
  (:e 5)
  (:f 6)
  (:g 7)
  ...
```

so I think it would be in the spirit of the library to add `(none)`. I will try it, and see if it works and make a PR if successful.

**Comment by resttime** [comment]
Possibly related as there's no IME support in Allegro5: https://github.com/liballeg/allegro5/issues/1191
