### ISSUE TITLE
Adding to QuickLisp

### ISSUE THREAD

**Issue by kalouantonis** [resttime/cl-liballegro#7]
Hi,

I added an issue ticket on quicklisp to get this package added to the repository. 

Unfortunately, the quicklisp maintainers are reporting some build issues for SBCL.

The issue is here.

https://github.com/quicklisp/quicklisp-projects/issues/971#issuecomment-124715523

Thanks.

**Comment by resttime** [comment]
Issue has been received and will be worked on after I sleep.

**Comment by resttime** [comment]
Hurray! cl-liballegro is now in the quicklisp repository.

**Comment by kalouantonis** [comment]
Thanks for taking the time to do this.

**Comment by resttime** [comment]
You're welcome. I was surprised to know there was interest in this project and the experience taught me a few things too.
