### ISSUE TITLE
Floating point error on OS X Yosemite with SBCL

### ISSUE THREAD

**Issue by kalouantonis** [resttime/cl-liballegro#8]
Hi again,

So, I've been struggling with this for a couple of days now. The library refuses to work on OS X. I've attempted to use both Clozure CL and SBCL with the same code. 

CCL doesn't give me any errors, it just loads the library when I use `(ql:quickload "cl-liballegro")` but then proceeds to "freeze" (as in become unresponsive) after I attempt to create a window with `(al:create-display 800 600)`.

SBCL gives me an arithmetic error, which I've seen before when attempting to use SDL2 with SBCL. I believe it has something to do with how SBCL handles threads and what not (This might help https://github.com/lispgames/cl-sdl2/issues/29). Here's the error output: 

```
* (main)

debugger invoked on a FLOATING-POINT-INEXACT in thread
#<THREAD "main thread" RUNNING {1002C0E913}>:
  arithmetic error FLOATING-POINT-INEXACT signalled

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

("bogus stack frame")
0]
```

I hope you can help as I'm really looking forward to using your library.

Regards,
Antonis.

**Comment by resttime** [comment]
I don't have an OS X machine or access to one so my support will be limited, though here's what I can think of right now.

First try the examples without SLIME if you haven't already. Also test x86 instead of x64 or vice versa. 

With SBCL try:
```cl
(sb-int:with-float-traps-masked (:invalid :inexact) (main))
```

**Comment by kalouantonis** [comment]
So, I gave it a go and I got some sort of result.

I get a blank unresponsive window that refuses to close, minimize or anything. SBCL gives me:

```
* (sb-int:with-float-traps-masked (:invalid :inexact) (main))

debugger invoked on a FLOATING-POINT-OVERFLOW in thread
#<THREAD "main thread" RUNNING {1002C0E913}>:
  arithmetic error FLOATING-POINT-OVERFLOW signalled

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

("bogus stack frame")
0]
```

**Comment by kalouantonis** [comment]
Looking at [this](https://github.com/sbcl/sbcl/blob/master/src/code/float-trap.lisp), I found the solution.

If I run with `(sb-int:with-float-traps-masked (:invalid :inexact :overflow) (main))` it works, though I wonder if there's a better solution to this. 

Do you have any idea what's causing this? Maybe I can attempt to find a fix somewhere?

**Comment by resttime** [comment]
If it works, cool. I'll keep the issue open and rename the title since others might run into the same problem.

Tried to look into the specfics and asked around. It might be a SBCL problem for how the traps are initialized with different threads on OS X. It might be a runtime problem with liballegro5 where there are some floating point operations. It might be an OS X problem which throws these errors in it's own Cocoa code somewhere. Others seem to have experienced related things with different libraries.

If it's not a thread issue, another solution is to mask the traps globally if they aren't already set, but I'm not sure what the full implications of that would be for debugging future code.
```cl
(sb-int:set-floating-point-modes :traps (:invalid :inexact :overflow))
```

On Windows (:overflow :invalid :divide-by-zero) are on by default.
```cl
CL-USER> (sb-int:get-floating-point-modes)
(:TRAPS (:OVERFLOW :INVALID :DIVIDE-BY-ZERO) :ROUNDING-MODE :NEAREST
 :CURRENT-EXCEPTIONS (:INEXACT) :ACCRUED-EXCEPTIONS (:INEXACT) :FAST-MODE NIL
 :PRECISION :53-BIT)
```

**Comment by resttime** [comment]
Huh, I'll just assume people use my interface so this shouldn't be an issue: 11109288063c31c017c92e76fd811b65f7958687

**Comment by z3t0** [comment]
Do we just load interface.lisp to use your interface?

**Comment by resttime** [comment]
@z3t0 The interface gets automatically loaded with the entire cl-liballegro system. It's completely optional whether you want to use it or not.

I opened a new issue #9 if you need more help.
