### ISSUE TITLE
Need support or have a question about the library? Stop by and drop an issue here!

### ISSUE THREAD

**Issue by resttime** [resttime/cl-liballegro#9]
I'm alive. Ask freely about anything pertaining to the library here and I'll see how I can help.

**Comment by resttime** [comment]
#10

**Comment by resttime** [comment]
#11

**Comment by RyanBurnside** [comment]
Hello resttime, not sure if you're an IRC user but currently we have a small community of people working on CL games and engines on FreeNode channel #lispgames. Feel free to stop by and share. This looks like a great project. We could also add your wrapper here: https://github.com/lispgames/lispgames.github.io/wiki/Common-Lisp

**Comment by resttime** [comment]
Oh hey, I don't particularly visit IRC anymore except on occasion. Maybe I'll drop in some time in the summer later. Feel free to add the wrapper to the wiki if you'd like though. As far as functionality goes, it's in a fully working state.

**Comment by resttime** [comment]
There's a github discussions thing now which I assume can take care of this: https://github.com/resttime/cl-liballegro/discussions
